### ISSUE TITLE
Reverse engineering method?

### ISSUE THREAD

**Issue by widarlein** [ikarulus/nextbike-api-reverse-engineering#1]
Hi!
Sorry for opening an issue like this, but I was just very interested in knowing what method you used for reverse engineering the api? I'm trying to analyze an api of another app myself, but could use some pointers!

**Comment by cybre-finn** [comment]
Sure.
It's been a while now, but in this case it was essentially a mixture of the handy circumstance that the predecessor nextbike app did just load a webview from a server (webview.nextbike.de or something, see README). From there I simply used the web dev tools of my firefox to intercept the api calls.

Yet first I didn't now about that handy circumstance. First attempt was to decompile the sources via [apktool](https://ibotpeaches.github.io/Apktool/) to SMALI (android's java runtime assembly language afaik) and try to analyze it.
By doing so I found out that searching for http endpoints (search eg. "https://") was a good idea. That way I found the webview application in the older app and got some other endpoints in the newer app.

If there wasn't that happy curcumstance with the webview I could have used a rooted android phone to intercept the http calls before they're getting encrypted (I guess) or even get deep into the SMALI assembly to get the logic behind the endpoints.

If there are any questions regarding your specific problem that you think doesn't belong here, just ping me via email. I am by far not an expert in reverse engineering but still happy to guide.

Happy hacking!
